const test=require('node:test');const assert=require('node:assert/strict');require('./cloze-data.js');
for(const lesson of CLOZE_LESSONS)test(lesson.id+' has three valid contexts per target',()=>{assert.ok(lesson.variants&&lesson.rounds);const groups=new Map();const ids=new Set();for(const q of lesson.questions){assert.ok(q.target&&q.translation&&q.explanation);assert.equal((q.sentence.match(/____/g)||[]).length,1,q.id);assert.ok(!ids.has(q.id));ids.add(q.id);const list=groups.get(q.target)||[];list.push(q);groups.set(q.target,list);if(lesson.mode!=='typed'){assert.equal(q.options.length,lesson.grade===1?2:3);assert.equal(new Set(q.options).size,q.options.length);assert.ok(q.options.includes(q.answer),q.id);}}for(const [target,qs] of groups){assert.equal(qs.length,3,target);assert.equal(new Set(qs.map(q=>q.sentence)).size,3,target);}assert.equal(groups.size,lesson.grade<3?(lesson.grade===2&&lesson.unit===6?15:lesson.grade===2&&lesson.unit===5?13:lesson.grade===1&&lesson.unit===8?12:10):lesson.grade===3?(lesson.unit===1?13:lesson.unit===2?14:15):lesson.grade===6?(lesson.unit===1?25:20):lesson.grade===4?(lesson.unit===1||lesson.unit===5?16:lesson.unit===4?26:15):20);});

test('grade 5 U3 covers every textbook word with three contexts and required case',()=>{require('./words.js');const lesson=CLOZE_LESSONS.find(l=>l.id==='g5-u3-v1');const unit=WORD_UNITS.find(u=>u.grade===5&&Number(u.number)===3);assert.equal(lesson.questions.length,60);for(const word of unit.words)assert.equal(lesson.questions.filter(q=>q.answer===word[0]).length,3,word[0]);assert.equal(lesson.mode,'typed');assert.match(lesson.source,/2025/);});

test('grade 5 U4 covers every textbook word with three contexts',()=>{require('./words.js');const lesson=CLOZE_LESSONS.find(l=>l.id==='g5-u4-v1');const unit=WORD_UNITS.find(u=>u.grade===5&&Number(u.number)===4);assert.equal(lesson.questions.length,60);for(const word of unit.words)assert.equal(lesson.questions.filter(q=>q.answer===word[0]).length,3,word[0]);assert.equal(lesson.mode,'typed');assert.match(lesson.source,/2025/);assert.equal(lesson.questions.filter(q=>q.answer==="won't").length,3);});

test('grade 4 U1 covers all textbook forms',()=>{require('./words.js');const lesson=CLOZE_LESSONS.find(l=>l.id==='g4-u1-v1'),unit=WORD_UNITS.find(u=>u.grade===4&&Number(u.number)===1);assert.equal(lesson.questions.length,48);for(const w of unit.words)assert.equal(lesson.questions.filter(q=>q.answer===w[0]).length,3,w[0]);assert.equal(lesson.mode,'typed');});

test('grade 4 U2 covers all textbook words',()=>{require('./words.js');const lesson=CLOZE_LESSONS.find(l=>l.id==='g4-u2-v1'),unit=WORD_UNITS.find(u=>u.grade===4&&Number(u.number)===2);assert.equal(lesson.questions.length,45);for(const w of unit.words)assert.equal(lesson.questions.filter(q=>q.answer===w[0]).length,3,w[0]);assert.equal(lesson.mode,'typed');});

test('grade 4 U3 covers all textbook words and phrases',()=>{require('./words.js');const lesson=CLOZE_LESSONS.find(l=>l.id==='g4-u3-v1'),unit=WORD_UNITS.find(u=>u.grade===4&&Number(u.number)===3);assert.equal(lesson.questions.length,45);for(const w of unit.words)assert.equal(lesson.questions.filter(q=>q.answer===w[0]).length,3,w[0]);assert.equal(lesson.mode,'typed');});

test('grade 4 U4 covers every base and past form',()=>{require('./words.js');const lesson=CLOZE_LESSONS.find(l=>l.id==='g4-u4-v1'),unit=WORD_UNITS.find(u=>u.grade===4&&Number(u.number)===4);assert.equal(lesson.questions.length,78);for(const w of unit.words)assert.equal(lesson.questions.filter(q=>q.answer===w[0]).length,3,w[0]);assert.equal(lesson.mode,'typed');});

test('grade 3 U1 covers all textbook words and phrases',()=>{require('./words.js');const lesson=CLOZE_LESSONS.find(l=>l.id==='g3-u1-v1'),unit=WORD_UNITS.find(u=>u.grade===3&&Number(u.number)===1);assert.equal(lesson.questions.length,39);for(const w of unit.words)assert.equal(lesson.questions.filter(q=>q.answer===w[0]).length,3,w[0]);assert.equal(lesson.mode,'typed');});

test('grade 3 U2 covers every textbook word and phrase',()=>{require('./words.js');const lesson=CLOZE_LESSONS.find(l=>l.id==='g3-u2-v1'),unit=WORD_UNITS.find(u=>u.grade===3&&Number(u.number)===2);assert.equal(lesson.questions.length,42);for(const w of unit.words)assert.equal(lesson.questions.filter(q=>q.answer===w[0]).length,3,w[0]);assert.equal(lesson.mode,'typed');});

test('grade 3 U3 covers every textbook word',()=>{require('./words.js');const lesson=CLOZE_LESSONS.find(l=>l.id==='g3-u3-v1'),unit=WORD_UNITS.find(u=>u.grade===3&&Number(u.number)===3);assert.equal(lesson.questions.length,45);for(const w of unit.words)assert.equal(lesson.questions.filter(q=>q.answer===w[0]).length,3,w[0]);assert.equal(lesson.mode,'typed');});

test('grade 3 U4 covers every textbook word and phrase',()=>{require('./words.js');const lesson=CLOZE_LESSONS.find(l=>l.id==='g3-u4-v1'),unit=WORD_UNITS.find(u=>u.grade===3&&Number(u.number)===4);assert.equal(lesson.questions.length,45);for(const w of unit.words)assert.equal(lesson.questions.filter(q=>q.answer===w[0]).length,3,w[0]);assert.equal(lesson.mode,'typed');});

test('grade 1 U5 covers all ten supplied words with three choice contexts',()=>{require('./words.js');const lesson=CLOZE_LESSONS.find(l=>l.id==='g1-u5-v1'),unit=WORD_UNITS.find(u=>u.grade===1&&u.id==='u5');assert.equal(unit.words.length,10);assert.equal(lesson.questions.length,30);for(const w of unit.words){assert.equal(lesson.questions.filter(q=>q.target===w[0]).length,3);assert.ok(require('node:fs').existsSync(w.audio),w.audio);}assert.ok(lesson.questions.every(q=>q.options.length===2));});

test('grade 2 U5 covers all months with three-choice questions and recordings',()=>{require('./words.js');const lesson=CLOZE_LESSONS.find(l=>l.id==='g2-u5-v1'),unit=WORD_UNITS.find(u=>u.grade===2&&u.id==='u5');assert.equal(unit.words.length,13);assert.equal(lesson.questions.length,39);for(const w of unit.words){assert.equal(lesson.questions.filter(q=>q.target===w[0]).length,3);assert.ok(require('node:fs').existsSync(w.audio));}assert.ok(lesson.questions.every(q=>q.options.length===3));});

test('grade 3 U5 covers all weekdays and activity words with recordings',()=>{require('./words.js');const lesson=CLOZE_LESSONS.find(l=>l.id==='g3-u5-v1'),unit=WORD_UNITS.find(u=>u.grade===3&&u.id==='u5');assert.equal(unit.words.length,15);assert.equal(lesson.questions.length,45);for(const w of unit.words){assert.equal(lesson.questions.filter(q=>q.answer===w[0]).length,3);assert.ok(require('node:fs').existsSync(w.audio));}assert.equal(lesson.mode,'typed');});

test('grade 6 U2 covers every textbook word with three typed contexts',()=>{require('./words.js');const lesson=CLOZE_LESSONS.find(l=>l.id==='g6-u2-v1'),unit=WORD_UNITS.find(u=>u.grade===6&&u.id==='u2');assert.equal(lesson.questions.length,60);for(const w of unit.words)assert.equal(lesson.questions.filter(q=>q.answer===w[0]).length,3,w[0]);assert.equal(lesson.mode,'typed');assert.match(lesson.source,/2023/);});

for(const n of [3,4])test('grade 6 U'+n+' covers all textbook words with verified forms',()=>{require('./words.js');const lesson=CLOZE_LESSONS.find(l=>l.id==='g6-u'+n+'-v1'),unit=WORD_UNITS.find(u=>u.grade===6&&u.id==='u'+n);assert.equal(lesson.questions.length,60);for(const w of unit.words)assert.equal(lesson.questions.filter(q=>q.answer===w[0]).length,3,w[0]);assert.equal(lesson.mode,'typed');assert.match(lesson.source,/2023/);});

test('grade 4 U5 covers all sixteen words and both verb forms with recordings',()=>{require('./words.js');const l=CLOZE_LESSONS.find(l=>l.id==='g4-u5-v1'),u=WORD_UNITS.find(u=>u.grade===4&&u.id==='u5');assert.equal(u.words.length,16);assert.equal(l.questions.length,48);for(const w of u.words){assert.equal(l.questions.filter(q=>q.answer===w[0]).length,3);assert.ok(require('node:fs').statSync(w.audio).size>1000);}assert.equal(l.mode,'typed');assert.ok(u.words.find(w=>w[0]==='lived')[2]);});

test('grade 5 U5 covers all textbook words, phrases and recordings',()=>{require('./words.js');const l=CLOZE_LESSONS.find(l=>l.id==='g5-u5-v1'),u=WORD_UNITS.find(u=>u.grade===5&&u.id==='u5');assert.equal(u.words.length,20);assert.equal(l.questions.length,60);for(const w of u.words){assert.equal(l.questions.filter(q=>q.answer===w[0]).length,3);assert.ok(require('node:fs').statSync(w.audio).size>1000);}assert.equal(l.mode,'typed');for(const answer of ['hike','hiking','Mexico','e-mail account'])assert.ok(l.questions.some(q=>q.answer===answer));});

test('grade 6 U5 covers all twenty words and lesson recordings',()=>{require('./words.js');const l=CLOZE_LESSONS.find(l=>l.id==='g6-u5-v1'),u=WORD_UNITS.find(u=>u.grade===6&&u.id==='u5');assert.equal(u.words.length,20);assert.equal(l.questions.length,60);for(const w of u.words){assert.equal(l.questions.filter(q=>q.answer===w[0]).length,3);assert.ok(require('node:fs').statSync(w.audio).size>1000);}assert.equal(l.mode,'typed');for(const a of ['invent','invention','Internet','powered by'])assert.ok(l.questions.some(q=>q.answer===a));});

test('grade 1 U6 covers ten words with two-choice contexts and recordings',()=>{require('./words.js');const l=CLOZE_LESSONS.find(l=>l.id==='g1-u6-v1'),u=WORD_UNITS.find(u=>u.grade===1&&u.id==='u6');assert.equal(u.words.length,10);assert.equal(l.questions.length,30);for(const w of u.words){assert.equal(l.questions.filter(q=>q.target===w[0]).length,3);assert.ok(require('node:fs').statSync(w.audio).size>1000);}assert.ok(l.questions.every(q=>q.options.length===2));assert.ok(l.questions.every(q=>!(q.options.includes('cannot')&&q.options.includes("can't"))));});

for(const n of [7,8])test('grade 1 U'+n+' covers every word with three choice contexts and recordings',()=>{require('./words.js');const l=CLOZE_LESSONS.find(l=>l.id==='g1-u'+n+'-v1'),u=WORD_UNITS.find(u=>u.grade===1&&u.id==='u'+n);assert.equal(u.words.length,n===7?10:12);assert.equal(l.questions.length,u.words.length*3);for(const w of u.words){assert.equal(l.questions.filter(q=>q.target===w[0]).length,3);assert.ok(require('node:fs').statSync(w.audio).size>1000);}assert.ok(l.questions.every(q=>q.options.length===2));});

for(const n of [9,10])test('grade 1 U'+n+' covers ten targets and recordings',()=>{require('./words.js');const l=CLOZE_LESSONS.find(l=>l.id==='g1-u'+n+'-v1'),u=WORD_UNITS.find(u=>u.grade===1&&u.id==='u'+n);assert.equal(u.words.length,10);assert.equal(l.questions.length,30);for(const w of u.words){assert.equal(l.questions.filter(q=>q.target===w[0]).length,3);assert.ok(require('node:fs').statSync(w.audio).size>1000);}assert.ok(l.questions.every(q=>q.options.length===2));if(n===10)assert.match(l.source,/2025/);});

test('grade 2 U6 covers all fifteen words with three choices and recordings',()=>{require('./words.js');const l=CLOZE_LESSONS.find(l=>l.id==='g2-u6-v1'),u=WORD_UNITS.find(u=>u.grade===2&&u.id==='u6');assert.equal(u.words.length,15);assert.equal(l.questions.length,45);for(const w of u.words){assert.equal(l.questions.filter(q=>q.target===w[0]).length,3);assert.ok(require('node:fs').statSync(w.audio).size>1000);}assert.ok(l.questions.every(q=>q.options.length===3));});
