const test=require('node:test');const assert=require('node:assert/strict');require('./cloze-data.js');
for(const lesson of CLOZE_LESSONS)test(lesson.id+' has three valid contexts per target',()=>{assert.ok(lesson.variants&&lesson.rounds);const groups=new Map();const ids=new Set();for(const q of lesson.questions){assert.ok(q.target&&q.translation&&q.explanation);assert.equal((q.sentence.match(/____/g)||[]).length,1,q.id);assert.ok(!ids.has(q.id));ids.add(q.id);const list=groups.get(q.target)||[];list.push(q);groups.set(q.target,list);if(lesson.mode!=='typed'){assert.equal(q.options.length,lesson.grade===1?2:3);assert.equal(new Set(q.options).size,q.options.length);assert.ok(q.options.includes(q.answer),q.id);}}for(const [target,qs] of groups){assert.equal(qs.length,3,target);assert.equal(new Set(qs.map(q=>q.sentence)).size,3,target);}assert.equal(groups.size,lesson.grade<3?10:lesson.grade===6?25:lesson.grade===4?(lesson.unit===1?16:lesson.unit===4?26:15):20);});

test('grade 5 U3 covers every textbook word with three contexts and required case',()=>{require('./words.js');const lesson=CLOZE_LESSONS.find(l=>l.id==='g5-u3-v1');const unit=WORD_UNITS.find(u=>u.grade===5&&Number(u.number)===3);assert.equal(lesson.questions.length,60);for(const word of unit.words)assert.equal(lesson.questions.filter(q=>q.answer===word[0]).length,3,word[0]);assert.equal(lesson.mode,'typed');assert.match(lesson.source,/2025/);});

test('grade 5 U4 covers every textbook word with three contexts',()=>{require('./words.js');const lesson=CLOZE_LESSONS.find(l=>l.id==='g5-u4-v1');const unit=WORD_UNITS.find(u=>u.grade===5&&Number(u.number)===4);assert.equal(lesson.questions.length,60);for(const word of unit.words)assert.equal(lesson.questions.filter(q=>q.answer===word[0]).length,3,word[0]);assert.equal(lesson.mode,'typed');assert.match(lesson.source,/2025/);assert.equal(lesson.questions.filter(q=>q.answer==="won't").length,3);});

test('grade 4 U1 covers all textbook forms',()=>{require('./words.js');const lesson=CLOZE_LESSONS.find(l=>l.id==='g4-u1-v1'),unit=WORD_UNITS.find(u=>u.grade===4&&Number(u.number)===1);assert.equal(lesson.questions.length,48);for(const w of unit.words)assert.equal(lesson.questions.filter(q=>q.answer===w[0]).length,3,w[0]);assert.equal(lesson.mode,'typed');});

test('grade 4 U2 covers all textbook words',()=>{require('./words.js');const lesson=CLOZE_LESSONS.find(l=>l.id==='g4-u2-v1'),unit=WORD_UNITS.find(u=>u.grade===4&&Number(u.number)===2);assert.equal(lesson.questions.length,45);for(const w of unit.words)assert.equal(lesson.questions.filter(q=>q.answer===w[0]).length,3,w[0]);assert.equal(lesson.mode,'typed');});

test('grade 4 U3 covers all textbook words and phrases',()=>{require('./words.js');const lesson=CLOZE_LESSONS.find(l=>l.id==='g4-u3-v1'),unit=WORD_UNITS.find(u=>u.grade===4&&Number(u.number)===3);assert.equal(lesson.questions.length,45);for(const w of unit.words)assert.equal(lesson.questions.filter(q=>q.answer===w[0]).length,3,w[0]);assert.equal(lesson.mode,'typed');});

test('grade 4 U4 covers every base and past form',()=>{require('./words.js');const lesson=CLOZE_LESSONS.find(l=>l.id==='g4-u4-v1'),unit=WORD_UNITS.find(u=>u.grade===4&&Number(u.number)===4);assert.equal(lesson.questions.length,78);for(const w of unit.words)assert.equal(lesson.questions.filter(q=>q.answer===w[0]).length,3,w[0]);assert.equal(lesson.mode,'typed');});
